fix(r): Ensure CXX_STD is set everywhere (#1706)
Upon submitting adbcpostgresql to CRAN, there is now a build error for R
4.1 on Windows, which uses C++14 as its default standard if unspecified.
This gives:

```
g++ -std=gnu++14  -I"D:/RCompile/recent/R-4.2.3/include" -DNDEBUG -I../src -DADBC_EXPORT="" -D__USE_MINGW_ANSI_STDIO    -I"d:/rtools42/x86_64-w64-mingw32.static.posix/include"     -pedantic -O2 -Wall  -mfpmath=sse -msse2 -mstackrealign  -c connection.cc -o connection.o
In file included from connection.cc:37:
result_helper.h:37:8: error: 'optional' in namespace 'std' does not name a template type
   37 |   std::optional<double> ParseDouble() const {
      |        ^~~~~~~~
result_helper.h:37:3: note: 'std::optional' is only available from C++17 onwards
```


https://www.r-project.org/nosvn/R.check/r-oldrel-windows-x86_64/adbcpostgresql-00install.html